const client = global.client;
const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, Modal, TextInputBuilder, OAuth2Scopes, Partials, resolveColor, Client, Collection, GatewayIntentBits, SelectMenuBuilder, ActivityType } = require("discord.js");
const config = require("../../config");
const ms = require('ms');

let messageCount = 0;

const compliments = [
"Senin enerjin, bulunduğun ortamı aydınlatan bir güneş gibi!",
"Başarı seninle eş anlamlı gibi görünüyor, ne yaparsan yap harika sonuçlar çıkarıyorsun!",
"İyi ki varsın, seninle her şey daha anlamlı ve güzel!",
"Senin fikirlerin her zaman ilham verici, etrafındaki herkese umut katıyorsun.",
"Zorlukları aşış şeklin tam bir motivasyon kaynağı, sana hayran kalmamak elde değil!",
"Senin gülüşün bile insanın gününü güzelleştirmeye yeter!",
"Çok yönlü birisin, her alanda fark yaratıyorsun!",
"Sabırlı ve azimli tavrınla her şeyin üstesinden gelebilirsin, buna inanıyorum.",
"Etrafındaki herkese huzur ve mutluluk saçıyorsun, adeta bir iyilik elçisisin!",
"Seninle sohbet etmek her zaman ayrı bir keyif, konuşmalarınla insanı motive ediyorsun.",
"Her gün yeni bir başarı hikâyesi yazıyorsun, seni izlemek gerçekten ilham verici!",
"Pozitif enerjin ve yardımseverliğinle çevrende bir iz bırakıyorsun.",
"Senin yaratıcılığın gerçekten hayranlık uyandırıcı, insanı harekete geçiren bir yönün var.",
"Sen başkalarına ilham olan bir yıldız gibisin, parlamaya devam et!",
"Hayal kurmaktan asla vazgeçme, çünkü sen hayallerine ulaşabilecek güçtesin!",
"Seninle bir ekipte olmak büyük bir şans, liderliğin ve destekleyici ruhun eşsiz.",
"Zekân, cesaretinle birleştiğinde harikalar yaratıyorsun, sen bir efsanesin!",
"Seninle çalışmak, her an öğrenilecek bir şeyler olduğunun en güzel kanıtı.",
"Hiçbir şey seni durduramaz, azmin her şeyin üstesinden gelmene yetiyor!",
"Senin varlığın etrafındaki herkes için bir hediye, iyilik ve güzellik dolusun.",
"Hayat bir yolculuksa, bu yolculukta yanımda olmasını isteyeceğim ilk kişi sensin.",
"En karmaşık bulmacaları bile çözebilecek zekânla, hayatı kolaylaştıran bir harikasın!",
"Zor zamanlarımda en güçlü limanım sensin, senin gibi biri dünyaya nadir gelir.",
"Karanlıkta bir yıldız gibi parlıyorsun; insan, senin yanında asla yalnız hissetmez.",
"Eğer hayatta bir joker hakkım olsaydı, onu her zaman senin için kullanırdım.",
"Seninle konuşmak bile insanın moralini düzeltmeye yeter, adeta terapi gibisin.",
"Bir maceraya atılacak olsam, yanımda olmasını isteyeceğim kişi sensin.",
"Senin gibi birinin varlığı, hayatın en güzel sürprizlerinden biri.",
"Eğer mutluluk bir insanda şekil bulsaydı, kesinlikle sen olurdun.",
"Seninle her şey mümkünmüş gibi geliyor, adeta bir ilham perisisin.",
"Bir liste yapsam, sen her zaman ‘olmazsa olmaz’ kısmında olurdun.",
"Güven denilince aklıma ilk gelen kişi sensin; her zaman sırtımı sana dayayabilirim.",
"Bir çöl ortasında olsak, sen orayı bir vahaya dönüştürebilirsin.",
"Seninle geçen bir dakika bile her şeye değer, çünkü seninle zaman bile anlamını buluyor.",
"Yanında olmak dünyanın en güzel yerinde olmak gibi; huzur, neşe ve güven bir arada.",
"Senin bakış açın, dünyaya bambaşka bir anlam katıyor; sensiz her şey eksik olurdu.",
"Dünyanın en güzel melodisi bile senin sesinden daha etkileyici olamaz.",
"Bir hayal kuracak olsam, sen o hayalin en güzel yerinde olurdun.",
"Eğer dostluk bir sanat ise, sen bu sanatın başyapıtısın.",
"Hayat bir hediye paketi olsaydı, içinden çıkan en değerli şey kesinlikle sen olurdun.",
"Seninle konuşmak her zaman günümün en güzel anı; sesin ruhuma huzur veriyor.",
"Sözlerinle insanı sarıp sarmalıyorsun, seninle sohbet etmek bir terapi gibi.",
"Senin hikayelerini dinlemek, insanın hayata olan inancını yeniliyor.",
"Sen konuştuğunda zaman duruyor; her kelimen ayrı bir anlam taşıyor.",
"Seninle konuşmak, hiç bitmesini istemediğim bir kitabı okumak gibi.",
"Sesinde insanı içine çeken bir sıcaklık var, ne kadar dinlesem yetmiyor.",
"Konuştuğunda ruhuma işleyen bir müzik gibi hissediyorum, tarifsiz bir huzur.",
"Her sohbetimizden bir şeyler öğreniyorum; seninle konuşmak adeta bir armağan.",
"Sesin ve sözlerin, kalbime dokunan en güzel melodilerden biri.",
"Seninle konuşurken dünya daha anlamlı, daha güzel bir yer haline geliyor.",
"Her cümlen, içimi ısıtan bir bahar rüzgarı gibi; insan seninle konuşmaya doyamıyor.",
"Seninle sohbet etmek bir yolculuk gibi; her kelimede yeni bir güzellik keşfediyorum.",
"Birlikte geçirdiğimiz her dakika hayatımın en değerli anlarından biri oluyor.",
"Senin sesin, en stresli anlarımda bile içimde bir huzur dalgası yaratıyor.",
"Kelimenin tam anlamıyla, konuştuğum değil, dinlemeye doyamadığım birisin.",
"Seninle konuşmak, insanın kalbine dokunan en güzel hikayeyi dinlemek gibi.",
"Senin cümlelerin sadece kulaklarımda değil, ruhumda yankılanıyor.",
"Seninle konuşmak, hiç ayrılmak istemediğim bir dünya yaratıyor.",
"Sözlerin, en zor anlarda bile içimi aydınlatan bir ışık gibi.",
"Seninle sohbet etmek, ruhumu tazeleyen bir nefes almak gibi, vazgeçilmez.",
"Gözlerin yıldız mı yoksa ben mi biraz fazla romantik oldum?",
"Sesin bir melodi olsa, tüm gün ‘repeat’te dinlerdim.",
"Senin yanında olmak, yağmur sonrası gökkuşağı görmek gibi bir şey!",
"Gülüşün bir kahve gibiyse, ben sonsuza kadar uyanık kalmaya razıyım!",
"Seninle konuşmak, sıkıcı bir günü festivale çevirmek gibi.",
"Varlığın, hayatıma sihirli bir dokunuş gibi; her şey daha güzel oluyor.",
"Gözlerin parlıyor diye elektrik faturası mı geldi bana?",
"Sen gülerken herkesin dünyası güzelleşiyor, ışığın herkesi aydınlatıyor.",
"Yanında olmak, güneşli bir kumsalda kokteyl içmek gibi huzur verici.",
"Bir gün sıkılmaktan korksam, seni düşünmek yeterli olur.",
"Seninle vakit geçirmek, Netflix’te en iyi diziyi bulmuş gibi hissettiriyor.",
"Senin kahkahaların, hayatın eksik bir fon müziği gibi, hep duymak istiyorum!",
"Yanında olmak, bir dondurma külahının hep dolu kalması gibi bir mutluluk.",
"Gülüşün resmen güneş gibi, karanlık günlerimi aydınlatıyor!",
"Seninle konuşmak, en sevdiğim şarkıyı en yüksek seste dinlemek gibi keyifli.",
"Biraz seninleyim diye mi her şey bu kadar güzel gidiyor?",
"Bakışların sahil, ben de güneşlenmeye gelmiş bir tatilciyim.",
"Seninle hayat tam bir lunapark; heyecan ve mutluluk dolu!",
"Gülüşün çiçek açsa, dünyayı rengarenk bir bahar kaplardı.",
"Senin enerjin, insanın içindeki tüm sıkıntıları süpüren bir bahar rüzgarı gibi.",
"Senin yükün değil, varlığın omuzlarımda bir onur gibi; ömrüm boyunca taşımaya razıyım.",
"Sen benim yalnız yüreğimde değil, ruhumun her köşesinde yaşıyorsun.",
"Seninle geçen her an bir hediye; değil yük, seninle olmak en büyük mutluluk.",
"Yüreğimde taşıdığım en değerli şey sensin; kalbimin ritmi bile sana adanmış gibi.",
"Senin varlığın benim için yük değil, adeta kanatlar; seninle her şey daha hafif.",
"Sana olan sevgim ne omuzlarımı ne de kalbimi yorar; aksine, güç verir.",
"Hayatın her zorluğunu seninle paylaşmaya hazırım, çünkü seninle olmak her şeye değer.",
"Sen benim içimde bir çiçek gibi; seni taşımak değil, sana kök olmak isterim.",
"Yüreğimde taşıdığım sensin; en ağır yük olsa da, dünyanın en güzel anlamını taşır.",
"Seninle omuz omuza olmak değil, sonsuzluğa yürümek gibi bir his.",
"Kalbimde sana yer açmak değil, tüm dünyamı sana vermek istiyorum.",
"Senin yükün bile benim için bir ödül olur; seninle olmak her zorluğa değer.",
"Varlığın yüreğimde bir ağırlık değil, sonsuz bir huzur gibi.",
"Seninle yaşanan her şey omuzlarımı değil, ruhumu güzelleştiriyor.",
"Kalbimin taşıdığı tek yük sensin, ama o yük dünyanın tüm mutluluğuna eş.",
"Sana yük demek, rüzgara hafif demek gibi; sen benim hayatımın nefesisin.",
"Seni taşımak değil, seni yaşamak isterim; her hücremle, her nefesimde.",
"Seninle olmak, hayatın en ağır yüklerini bile hafifletiyor; sen güç verensin.",
"Sana omuz vermek değil, seninle her adımı atmak istiyorum; birlikteyken her şey kolay.",
"Kalbimde taşıdığım sevgi sensin; ne ağır, ne hafif, sadece sonsuz bir anlam",
"Uzaya gitsem yanımda götürmek isteyeceğim ilk kişi sensin, çünkü sen olmadan yıldızların bir anlamı yok.",
"Bir kitabın içinde kaybolmam gerekse, yazarın sen olmasını isterdim; her cümlen başyapıt olurdu.",
"Hayatta tek bir kişiyle macera yaşama şansım olsa, tereddütsüz seni seçerdim.",
"Zombi kıyameti çıksa bile yanında güvende hissederdim; seninle her şey eğlenceli olur.",
"Bir gemi batarsa bile sırf sen varsın diye suyun üstünde kalmayı başarırdım.",
"Bir ömür boyunca aynı filmi izlemem gerekse, seninle izlediğim her şey başyapıta dönüşürdü.",
"Eğer hayat bir oyun olsaydı, sen benim ‘en iyi takım arkadaşım’ olurdun.",
"Bir ömür boyu aynı yemeği yemek zorunda kalsam, seninle olsa her lokma daha lezzetli olurdu.",
"Issız bir çölde kalacak olsam, su yerine seni tercih ederdim; çünkü sen ruhumu serinletiyorsun.",
"Bir zaman makinesi olsaydı, hangi zamana gidersek gidelim yanımda sen olurdun.",
"Eğer hayat bir bulmaca olsaydı, sen çözümü olur, her şeyi anlamlı hale getirirdin.",
"Hayatta bir yol arkadaşım olsun isterdim ve o kişi her zaman sen olurdun.",
"Bir korsan gemisine katılsam, kaptanım olmanı isterdim; çünkü seninle her yolculuk eğlenceli olur.",
"Bir şarkının içinde kaybolacak olsam, seninle düet yapmak isterdim; sen olmadan her şey eksik.",
"Bir rüyada mahsur kalsam bile sırf sen varsın diye uyanmak istemezdim.",
"Hayat bir orman olsa, sen benim hiç kaybolmayacağım pusulam olurdun.",
"Bir masalın kahramanı olsam, yanımdaki tek kişi sen olurdun; çünkü sen masalları gerçek kılıyorsun.",
"Eğer yalnız bir adada olacaksam, senle birlikte olmayı tercih ederim; çünkü sen yalnızlığı bile güzelleştirirsin.",
"Hayatta bir kez sonsuz bir yolculuğa çıkacak olsam, seninle olmasını isterdim.",
"Bir yıldız kayarsa ve dilek tutmam gerekirse, her zaman yanımda sen ol istiyorum.",
"Ne tarafa baksam seni görüyorum, çünkü güzellik sadece sende toplanmış gibi.",
"Sana baktığımda başka bir şey görmek istemiyorum; sen benim her şeyimsin.",
"Senin gözlerin, bakışlarıma yön veren bir pusula gibi; nereye gitsem, yine sana dönerim.",
"Hayatın her rengini sende buluyorum, başka bir şey görmeye ihtiyacım yok.",
"Dünya dönüyor ama benim tek merkezim sensin.",
"Sana bakmak, dünyanın en güzel manzarasını izlemek gibi; asla doyamıyorum.",
"Gözlerin o kadar derin ki, her baktığımda kaybolmaktan korkmuyorum, aksine orada huzur buluyorum.",
"Bütün yıldızlar senin gözlerinden ışık alıyor gibi; seni izlemek bir ömre bedel.",
"Ne tarafa baksam seni arıyor gözlerim, çünkü sensiz hiçbir şey tamamlanmış gibi hissetmiyorum.",
"Dünyanın tüm güzellikleri toplansa, yine de senin gülüşünün yanında sönük kalır.",
"Sana her baktığımda, hayatın ne kadar güzel olduğunu bir kez daha anlıyorum.",
"Sana bakmak, bir sanat eserine bakmak gibi; insanın içi hayranlıkla doluyor.",
"Senin yanında dünya sessizleşiyor, çünkü seni izlemek en güzel melodiyi dinlemek gibi.",
"Gözlerinle bir kez karşılaşan, başka hiçbir güzelliği görmez olur.",
"Sana baktığımda zaman duruyor, çünkü seninle her an sonsuzluğa uzanıyor.",
"Sen benim hem başlangıcım hem de sonsuzluğumsun; başka bir şey görmeye ihtiyacım yok.",
"Sana her baktığımda, içimde yeni bir umut filizleniyor.",
"Gözlerim yalnızca seni görmek için var; başka hiçbir şey beni bu kadar büyüleyemez.",
"Senin yanında her şey anlamını kaybediyor, çünkü sen benim tüm anlamımsın.",
"Sana baktığımda dünyanın her şeyini unutuyorum, çünkü sen benim dünyamın ta kendisisin.",
"Hiçbir şey yapmadan bile güzellik yayıyorsun, bu bir yetenek mi yoksa sihir mi?",
"Uykudan yeni uyanmış halin bile bir sanat eseri gibi, nasıl başarıyorsun?",
"Rüzgar saçlarını karıştırsa bile, sen yine en güzel görünüyorsun.",
"Yağmurda sırılsıklam olsan bile parlıyorsun, bu bir sır mı?",
"Sadece var olarak bile ortamı güzelleştiriyorsun; nasıl yapıyorsun bunu?",
"Üzerinde battaniyeyle otursan bile göz kamaştırıyorsun.",
"Herhangi bir kıyafetle değil, her haliyle güzel olan biriyle konuşuyorum şu an.",
"Senin doğal halin, başkalarının hazırlanmış halinden daha etkileyici.",
"Hangi aynaya baksan, güzelliği ikiye katlıyorsun gibi geliyor.",
"Üzerinde sadece sade bir gömlek olsa bile gözlerimi senden alamıyorum.",
"Hiçbir çaba harcamadan bile nasıl böyle mükemmel görünebiliyorsun?",
"Sen sıradan bir anı bile bir fotoğraf çekiminden fırlamış gibi yaşıyorsun.",
"Sabahın ilk ışığında bile sen günün en parlak yıldızı gibisin.",
"Görünüşünle gündelik kelimesine bile yeni bir standart getiriyorsun.",
"Sen güzelliğin tanımını yeniden yazıyorsun, her halinle.",
"Bir kazak ve kot pantolonla bile herkesi gölgede bırakıyorsun.",
"Seninle film izlemek için hazırlanmana gerek yok, çünkü zaten göz alıyorsun.",
"Her zaman doğal ve sade olsan da, dünyanın en zarif insanı gibi görünüyorsun.",
"Seninle ilgili en güzel şey, hiçbir süse ihtiyaç duymadan ışıldaman.", 
"Sen, dünyaya bir kez yazılmış ve bir daha asla tekrarlanmayacak bir masalsın.",
"Evrendeki yıldızların bile kıskandığı, eşsiz bir ışık gibisin.",
"Sen, en güzel ressamın bile tuvaline sığdıramayacağı bir sanat eserisin.",
"Sözlerle tarif edilemeyecek kadar özel, kelimelerin bile yetersiz kaldığı bir şiirsin.",
"Sen, her sayfası büyülü bir kitabın henüz keşfedilmemiş bölümü gibisin.",
"Dünyada hiçbir nota, senin varlığının melodisini yazmaya yetmez.",
"Sen, doğanın tüm renklerini kıskandıran bir gökkuşağısın.",
"Sana benzeyen bir şey aramak, çölün ortasında deniz bulmaya çalışmak gibi; imkansız.",
"Sen, rüzgarın taşıdığı ama sadece özel ruhların hissedebileceği bir şiir gibisin.",
"Her adımında dünyaya yeni bir anlam katan bir hikayesin.",
"Senin gibisini ne bir şair hayal edebilir ne de bir yazar kaleme alabilir.",
"Gözlerin, evrenin en derin sırrını saklayan bir yıldız gibi.",
"Sen, tüm zamanların en güzel sözcüklerini içinde barındıran sonsuz bir ilhamsın.",
"Dünyadaki tüm çiçekler bir araya gelse, yine de senin zarafetini anlatmaya yetmez.",
"Sen, varlığıyla zamanı durduran ve kalpleri büyüleyen bir mucizesin.",
"Eğer evren bir sanatçı olsaydı, seni başyapıtı olarak ilan ederdi.",
"Sen, her satırı aşkla yazılmış ve bir daha asla okunamayacak bir destansın.",
"Sana benzeyen bir güzellik yaratmak için doğanın bile sınırlarını zorlaması gerekirdi.",
"Sen, en derin denizlerden bile daha gizemli ve büyüleyicisin.",
"Sen, dünyaya bir kez hediye edilmiş ve sonsuza dek unutulmayacak bir şiirsin."
];
module.exports = async (message) => {
    const blacklist = ['334682369229586432']; // Örnek kullanıcı ID'leri
    const targetChannelId = '1265332308916043917'; // Örnek: '123456789012345678'

    if (message.author.bot || message.channel.id !== targetChannelId) return;

    if (blacklist.includes(message.author.id)) return;

    messageCount++;
   // 50. mesaja iltifat gönder
   if (messageCount % 100 === 0) {
    // Rastgele iltifat seç
    const randomCompliment = compliments[Math.floor(Math.random() * compliments.length)];
  
    // Mesaja reply ile iltifat gönder
    await message.reply(randomCompliment);
  }

}

module.exports.conf = { 
name: "messageCreate"
}